name: planmate_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  app_links: ^6.4.1
  bloc_test: ^10.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.3
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fake_cloud_firestore: ^4.0.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_facebook_auth: ^7.1.2
  google_generative_ai: ^0.4.7
  google_sign_in: ^6.2.1
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
